In [13]:
# 2 задача
import numpy as np

a=np.random.random((6, 6))
print(a)
print(a.sum(axis=1)/a.min(axis=0))











[[0.28152877 0.18237159 0.97879338 0.00168799 0.12717059 0.06263739]
 [0.61649169 0.19337104 0.05540718 0.55137878 0.21129576 0.40228203]
 [0.51660334 0.91402539 0.4158992  0.56477673 0.15076299 0.12606577]
 [0.60753511 0.58756555 0.57061995 0.75911457 0.89548548 0.48319902]
 [0.34733743 0.53501194 0.41729962 0.08033601 0.63886559 0.41454417]
 [0.06013097 0.50509853 0.59180764 0.74173659 0.80447271 0.86266168]]
[  27.17717212   11.13236162   48.51597413 2312.51983927   19.13488595
   56.92938889]


In [15]:
#3 задача
import numpy as np
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
y = np.where (x==0)[0]-1
print(x[y].max())

7


In [2]:
# 1 задача
import numpy as np

def find_nearest(a, a0):
    "Element in nd array `a` closest to the scalar value `a0`"
    idx = np.abs(a - a0).argmin()
    return a.flat[idx]



array = np.random.random((10,3))
print(array)
value = 0.5
print(find_nearest(array, value))


[[0.13374266 0.5280255  0.26675273]
 [0.46385296 0.80850334 0.19801475]
 [0.19300559 0.07741552 0.36769675]
 [0.81179516 0.2969073  0.27063114]
 [0.93886168 0.44499955 0.67547765]
 [0.11150753 0.54505137 0.13503853]
 [0.50403753 0.84770998 0.39633201]
 [0.74982593 0.85127942 0.83258168]
 [0.47829932 0.56646599 0.93706294]
 [0.36383235 0.30544407 0.27846853]]
0.5040375261113215


In [3]:
#1 задача с for
import numpy as np

x1 = np.random.random([10,3])
print(x1)

c05 = [a[np.abs(a-0.5).argmin()] for a in x1]
print(c05)

[[0.58089711 0.76126648 0.71363047]
 [0.8600427  0.5932688  0.41082223]
 [0.01453731 0.91089844 0.48713819]
 [0.18799368 0.41821503 0.20610844]
 [0.50742628 0.50397771 0.6942207 ]
 [0.25253632 0.36989707 0.75624686]
 [0.71075619 0.30875047 0.42784513]
 [0.91322463 0.72684857 0.10325557]
 [0.84057616 0.73111325 0.56976276]
 [0.61329198 0.70948283 0.93497718]]
[0.5808971133968946, 0.4108222344862287, 0.4871381926774331, 0.4182150305268154, 0.5039777078935495, 0.36989706878955864, 0.42784513496567234, 0.7268485745774917, 0.5697627622373116, 0.613291980347234]


In [18]:
#4 задача
import numpy as np

x = np.ones(10)
print(x)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
print(i)
j = int(0)
print(j)
index = int(0)

while j < 8:
    index = i[j]
    print(index)
    x[index] += 1
    print(x)
    j += 1
    
print(x)




[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0 1 2 3 5 5 5 8]
0
0
[2. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
1
[2. 2. 1. 1. 1. 1. 1. 1. 1. 1.]
2
[2. 2. 2. 1. 1. 1. 1. 1. 1. 1.]
3
[2. 2. 2. 2. 1. 1. 1. 1. 1. 1.]
5
[2. 2. 2. 2. 1. 2. 1. 1. 1. 1.]
5
[2. 2. 2. 2. 1. 3. 1. 1. 1. 1.]
5
[2. 2. 2. 2. 1. 4. 1. 1. 1. 1.]
8
[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]
[2. 2. 2. 2. 1. 4. 1. 1. 2. 1.]


In [22]:
import numpy as np
a = np.arange(16).reshape(4, 4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [110]:
#5 задача

import numpy as np

a = np.arange(16).reshape(4, 4)
i = int(0)
j = int(0)
n = int(0)
t = int(0)
print("{ ", end = "")

while n < 7:
    print(n,":", end = "")
    print("[", end = "")
    while i < 4:
        while j < 4:
            if (i == (n - j)):
                print(a[i,j], end = " ")   
            j += 1
        i += 1
        j = 0
    print("]", end = "")
    print( "," if n != 6 else "" , end = " ")
    n += 1
    i = 0
    
print("}", end = "")

{ 0 :[0 ], 1 :[1 4 ], 2 :[2 5 8 ], 3 :[3 6 9 12 ], 4 :[7 10 13 ], 5 :[11 14 ], 6 :[15 ] }