In [13]:
# 2 задача
import numpy as np

a=np.random.random((6, 6))
print(a)
print(a.sum(axis=1)/a.min(axis=0))











[[0.28152877 0.18237159 0.97879338 0.00168799 0.12717059 0.06263739]
 [0.61649169 0.19337104 0.05540718 0.55137878 0.21129576 0.40228203]
 [0.51660334 0.91402539 0.4158992  0.56477673 0.15076299 0.12606577]
 [0.60753511 0.58756555 0.57061995 0.75911457 0.89548548 0.48319902]
 [0.34733743 0.53501194 0.41729962 0.08033601 0.63886559 0.41454417]
 [0.06013097 0.50509853 0.59180764 0.74173659 0.80447271 0.86266168]]
[  27.17717212   11.13236162   48.51597413 2312.51983927   19.13488595
   56.92938889]


In [15]:
#3 задача
import numpy as np
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
y = np.where (x==0)[0]-1
print(x[y].max())

7


In [31]:
# 1 задача
import numpy as np

def find_nearest(a, a0):
    "Element in nd array `a` closest to the scalar value `a0`"
    idx = np.abs(a - a0).argmin()
    return a.flat[idx]



array = np.random.random(10)
print(array)
value = 0.5
print(find_nearest(array, value))


[0.90314657 0.68413933 0.2705129  0.58661566 0.80288724 0.84579156
 0.83286521 0.79466068 0.88856818 0.41491525]
0.41491525293262976
